### ISSUE TITLE
Salut!

### ISSUE THREAD

**Issue by audiosistem** [angelitto2005/my.json.players#1]
![OpenMeta before](https://user-images.githubusercontent.com/6246768/78903155-6ad6fc00-7a83-11ea-8a14-f0645dc73a7a.jpg)
![OpenMeta after 1](https://user-images.githubusercontent.com/6246768/78903162-6ca0bf80-7a83-11ea-8607-afcb0d63e547.jpg)
![OpenMeta after 2](https://user-images.githubusercontent.com/6246768/78903172-6e6a8300-7a83-11ea-8dca-1f62366dcbd6.jpg)
![OpenMeta I want](https://user-images.githubusercontent.com/6246768/78903201-76c2be00-7a83-11ea-9d11-a3074d6b5597.jpg)
1.Before 2/3 After 4.I want

**Comment by angelitto2005** [comment]
Salut.
Am testat acum cu TheMovieDb Helper si cauta corect. Si stream si torrent. OpenMeta afiseaza doar torrentii. Poate pentru ca nu se mai ocupa nimeni de el si trebuie actualizat.
Daca o sa mai rezolv ceva, o sa te anunt.

![78910342-792a1580-7a8d-11ea-87ae-1ac8f588d30d](https://user-images.githubusercontent.com/29383306/78912395-374e9e80-7a90-11ea-8627-6e13e9fc1db6.jpg)

**Comment by audiosistem** [comment]
Nu am timp acum,dar cred ca daca te uiti,in ce are OpenMeta de la Crew,La plaza,Numbers,Temps...Nu vreau sa bag in nici un build torrenti.Am Bit separat,in unele tari au probleme.Am dezactivat din toate pluginurile,debrid si torr.Multumesc!O seara buna!
    On Thursday, April 9, 2020, 06:31:03 PM GMT+3, angelitto2005 <notifications@github.com> wrote:  
 
 


Salut.
Am testat acum cu TheMovieDb Helper si cauta corect. Si stream si torrent. OpenMeta afiseaza doar torrentii. Poate pentru ca nu se mai ocupa nimeni de el si trebuie actualizat.
Daca o sa mai rezolv ceva, o sa te anunt.

**Comment by audiosistem** [comment]
Trebuie modificat        "plugin://plugin.video.romanianpack/?action=searchSites&modalitate=edit&query={title}"                                    "plugin://plugin.video.romanianpack/?action=searchSites&modalitate=edit&query={showname}"        cu unele cu play.Ceva in genul att.
    On Thursday, April 9, 2020, 07:43:53 PM GMT+3, Albin Alexandrescu <audio2sistem@yahoo.com> wrote:  
 
  Nu am timp acum,dar cred ca daca te uiti,in ce are OpenMeta de la Crew,La plaza,Numbers,Temps...Nu vreau sa bag in nici un build torrenti.Am Bit separat,in unele tari au probleme.Am dezactivat din toate pluginurile,debrid si torr.Multumesc!O seara buna!
    On Thursday, April 9, 2020, 06:31:03 PM GMT+3, angelitto2005 <notifications@github.com> wrote:  
 
 


Salut.
Am testat acum cu TheMovieDb Helper si cauta corect. Si stream si torrent. OpenMeta afiseaza doar torrentii. Poate pentru ca nu se mai ocupa nimeni de el si trebuie actualizat.
Daca o sa mai rezolv ceva, o sa te anunt.

**Comment by angelitto2005** [comment]
Am inteles ce vrei dar fiecare plugin are un algoritm diferit de SEARCH. The Crew si Venom au algoritmul apropiat de Exodus. Dar MRSP e cu totul alta treaba. E mult mai complex si dupa cum am zis, problema e la OpenMeta. TheMovieDB Helper e un fel de OpenMeta combinat cu  OpenInfo, dar e intretinut. Si in el, merge fara probleme metaplayerul creat de mine. Apar si torentii si streamurile. iar daca opresc torentii din MRSP,, arata doar streamurile. 
Sincer, nu stiu ce sa-i mai fac. Eu sunt doar un simplu utilizator ca tine, care mi-am bagat putin nasul prin scripturi dar aici e nevoie de cineva cu experienta care sa-i dea de cap.

**Comment by audiosistem** [comment]
Problema cea mare e ca MRSP e un pack,nu un singur plugin video si de aici problema.
    On Thursday, April 9, 2020, 08:45:21 PM GMT+3, angelitto2005 <notifications@github.com> wrote:  
 
 


Am inteles ce vrei dar fiecare plugin are un algoritm diferit de SEARCH. The Crew si Venom au algoritmul apropiat de Exodus. Dar MRSP e cu totul alta treaba. E mult mai complex si dupa cum am zis, problema e la OpenMeta. TheMovieDB Helper e un fel de OpenMeta combinat cu OpenInfo, dar e intretinut. Si in el, merge fara probleme metaplayerul creat de mine. Apar si torentii si streamurile. iar daca opresc torentii din MRSP,, arata doar streamurile.
Sincer, nu stiu ce sa-i mai fac. Eu sunt doar un simplu utilizator ca tine, care mi-am bagat putin nasul prin scripturi dar aici e nevoie de cineva cu experienta care sa-i dea de cap.

**Comment by audiosistem** [comment]
Bun!Daca ai reusit pe The MovieDB,imi poti trimite fisierele de player si .storage...ma mut pe el si vad,daca pot renunta la OpenMeta.
    On Thursday, April 9, 2020, 08:45:21 PM GMT+3, angelitto2005 <notifications@github.com> wrote:  
 
 


Am inteles ce vrei dar fiecare plugin are un algoritm diferit de SEARCH. The Crew si Venom au algoritmul apropiat de Exodus. Dar MRSP e cu totul alta treaba. E mult mai complex si dupa cum am zis, problema e la OpenMeta. TheMovieDB Helper e un fel de OpenMeta combinat cu OpenInfo, dar e intretinut. Si in el, merge fara probleme metaplayerul creat de mine. Apar si torentii si streamurile. iar daca opresc torentii din MRSP,, arata doar streamurile.
Sincer, nu stiu ce sa-i mai fac. Eu sunt doar un simplu utilizator ca tine, care mi-am bagat putin nasul prin scripturi dar aici e nevoie de cineva cu experienta care sa-i dea de cap.

**Comment by audiosistem** [comment]
Atata doar ca nu scap de torr...Multumesc!O seara buna!Nu te mai deranjez!
    On Thursday, April 9, 2020, 08:58:39 PM GMT+3, Albin Alexandrescu <audio2sistem@yahoo.com> wrote:  
 
  Bun!Daca ai reusit pe The MovieDB,imi poti trimite fisierele de player si .storage...ma mut pe el si vad,daca pot renunta la OpenMeta.
    On Thursday, April 9, 2020, 08:45:21 PM GMT+3, angelitto2005 <notifications@github.com> wrote:  
 
 


Am inteles ce vrei dar fiecare plugin are un algoritm diferit de SEARCH. The Crew si Venom au algoritmul apropiat de Exodus. Dar MRSP e cu totul alta treaba. E mult mai complex si dupa cum am zis, problema e la OpenMeta. TheMovieDB Helper e un fel de OpenMeta combinat cu OpenInfo, dar e intretinut. Si in el, merge fara probleme metaplayerul creat de mine. Apar si torentii si streamurile. iar daca opresc torentii din MRSP,, arata doar streamurile.
Sincer, nu stiu ce sa-i mai fac. Eu sunt doar un simplu utilizator ca tine, care mi-am bagat putin nasul prin scripturi dar aici e nevoie de cineva cu experienta care sa-i dea de cap.

**Comment by angelitto2005** [comment]
MetaPlayerul pentru ”TheMovieDb Helper” e aici la mine in repo. Se numeste ”mrsp.json”. Il bagi in
AppData\Roaming\Kodi\userdata\addon_data\plugin.video.themoviedb.helper\players\
Creezi manual folderul ”Players” daca nu il ai. Apoi il recunoaste automat

**Comment by audiosistem** [comment]
Facut...m-am apucat de restul.Multumesc mult!
    On Thursday, April 9, 2020, 09:37:55 PM GMT+3, angelitto2005 <notifications@github.com> wrote:  
 
 


MetaPlayerul pentru ”TheMovieDb Helper” e aici la mine in repo. Se numeste ”mrsp.json”. Il bagi in
AppData\Roaming\Kodi\userdata\addon_data\plugin.video.themoviedb.helper\players
Creezi manual folderul ”Players” daca nu il ai. Apoi il recunoaste automat

**Comment by angelitto2005** [comment]
Your wellcome!  Daca vrei players pentru TMDB Helper, ii poti descarca de aici: 
https://bit.ly/tmdbplayers

**Comment by audiosistem** [comment]
REZOLVAT!
    On Thursday, April 9, 2020, 11:35:37 PM GMT+3, angelitto2005 <notifications@github.com> wrote:  
 
 


Your wellcome! Daca vrei players pentru TMDB Helper, ii poti descarca de aici:
https://bit.ly/tmdbplayers

**Comment by audiosistem** [comment]
Build Al3inA 1.0.5 up.https://silevasile.me/repo/
    On Friday, April 10, 2020, 12:07:00 AM GMT+3, Albin Alexandrescu <audio2sistem@yahoo.com> wrote:  
 
  REZOLVAT!
    On Thursday, April 9, 2020, 11:35:37 PM GMT+3, angelitto2005 <notifications@github.com> wrote:  
 
 


Your wellcome! Daca vrei players pentru TMDB Helper, ii poti descarca de aici:
https://bit.ly/tmdbplayers

**Comment by audiosistem** [comment]
Salut!Pe 11 apr. 2020 17:37, angelitto2005 <notifications@github.com> a scris:
Closed #1.
